<table align="left">
  <td>
<a href="https://colab.research.google.com/github/marco-canas/didactica_ciencia_datos/blob/main/1_curso_machine_learning/1_python/2_estructuras_datos/5_dataframe/1_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
 </td>
</table>

Obtenga el programa del curso [aquí]()

# 5 DataFrame de Pandas

Dame, por favor, un diseño de clase sobre la estructura de datos llamada DataFrame de Pandas en python y su utilización en ciencia de datos con técnicas de machine learning siguiendo la siguiente estructura: 
1. Título de la clase 
2. Objetivo de aprendizaje
3. Contenido de la clase
4. Actividades de aprendizaje
5. Tarea o actividades de ejercitación y fijación
6. Diseño de actividad de retroalimentación.

Aquí tienes un diseño de clase sobre la estructura de datos `DataFrame` en Pandas para su aplicación en ciencia de datos y técnicas de machine learning.

---


### 1. Título de la Clase
**Introducción a la estructura DataFrame en Pandas y su Aplicación en Ciencia de Datos con técnicas Machine Learning**


### 2. Objetivo de Aprendizaje

Al finalizar esta clase, los estudiantes serán capaces de:
- Crear y manipular Series y DataFrames en Pandas.
- Explorar y limpiar datos utilizando métodos de Pandas.
- Aplicar operaciones comunes de ciencia de datos en DataFrames para la preparación de datos en proyectos de machine learning.


### 3. Contenido de la Clase

1. **Introducción a Pandas y a la Estructura de Datos `DataFrame`**
   - ¿Qué es Pandas y por qué es fundamental en ciencia de datos?
   - Definición y características de un `DataFrame`.
   - Comparación de `DataFrame` con otras estructuras de datos (listas, nd-arrays).

<img src = 'https://i.ytimg.com/vi/SMkoyjFdVGY/sddefault.jpg'>


2. **Creación de DataFrames**
   - Creación de `DataFrames` a partir de listas, diccionarios, y archivos (CSV, Excel).
   - Exploración de datos con funciones como `head()`, `tail()`, `info()`, y `describe()`.


3. **Manipulación de Datos en un DataFrame**
   - Selección y filtrado de datos: acceso a filas y columnas.
   - Modificación de valores, creación y eliminación de columnas.
   - Manejo de valores nulos y duplicados.


4. **Operaciones de Limpieza y Transformación de Datos**
   - Métodos para limpiar datos y eliminar registros incompletos.
   - Transformación de tipos de datos.
   - Uso de funciones como `apply()`, `groupby()`, y `merge()`.


5. **Preparación de Datos para Machine Learning**
   - Normalización y estandarización de datos numéricos.
   - Codificación de variables categóricas.
   - División de los datos en conjuntos de entrenamiento y prueba.


### 4. Actividades de Aprendizaje


1. **Exploración de DataFrames**: Cargar un archivo CSV con datos de ejemplo (por ejemplo, el conjunto de datos de Titanic) y explorar sus características principales usando `head()`, `info()`, y `describe()`.


2. **Manipulación Básica**: Seleccionar y modificar columnas, crear nuevas columnas a partir de otras, y filtrar datos basándose en condiciones.


3. **Limpieza de Datos**: Usar métodos para manejar valores nulos y eliminar registros duplicados. Transformar tipos de datos de columnas según se necesite.


4. **Transformación y Agrupación**: Aplicar `groupby()` para obtener estadísticas agregadas y usar `apply()` para crear nuevas características a partir de columnas existentes.


5. **Preparación de Datos para Machine Learning**: Estandarizar las columnas numéricas y codificar las variables categóricas. Dividir el conjunto de datos en entrenamiento y prueba.


### 5. Tarea o Actividades de Ejercitación y Fijación

1. **Ejercicio de Exploración y Modificación**: 
   - Cargar un archivo CSV (se puede sugerir un conjunto de datos abierto como el de "Iris" o "Heart Disease").
   - Realizar un análisis exploratorio con `head()`, `tail()`, `info()`, y `describe()`.


2. **Ejercicio de Limpieza y Transformación**:
   - Identificar y manejar valores nulos en el conjunto de datos.
   - Eliminar duplicados y cambiar tipos de datos de columnas según su contenido.


3. **Ejercicio de Preparación para Machine Learning**:
   - Estandarizar una columna numérica y realizar una codificación `One-Hot Encoding` de una columna categórica.
   - Dividir el conjunto de datos en conjuntos de entrenamiento y prueba, e indicar el porcentaje de división.


### 6. Diseño de Actividad de Retroalimentación

**Actividad de Retroalimentación: Proyecto Colaborativo en Ciencia de Datos**

1. **Descripción de la Actividad**:
   En grupos, los estudiantes trabajarán en un conjunto de datos de su elección (pueden seleccionar uno de Kaggle o un dataset abierto). Cada grupo debe presentar un informe en el que:
   - Describan el conjunto de datos (incluyendo características y problemas de calidad).
   - Apliquen técnicas de limpieza y transformación en el `DataFrame` para prepararlo para el análisis.
   - Realicen una división en conjuntos de entrenamiento y prueba, preparando el dataset para su uso en machine learning.


2. **Objetivo de la Retroalimentación**:
   La actividad tiene como propósito que los estudiantes compartan sus hallazgos y reciban retroalimentación sobre la calidad de sus datos y la adecuación de sus pasos de preparación, abordando errores comunes en el preprocesamiento de datos.


3. **Presentación y Discusión**:
   Cada grupo compartirá su informe en clase, mostrando el código y los resultados obtenidos. Los compañeros de clase y el instructor brindarán retroalimentación, sugiriendo mejoras o alternativas para un preprocesamiento de datos más efectivo.

---


Este diseño de clase guía a los estudiantes en el aprendizaje práctico y conceptual de los DataFrames en Pandas, y su importancia en el flujo de trabajo de machine learning. La retroalimentación colaborativa refuerza su comprensión y mejora sus habilidades de preparación de datos, esenciales para la ciencia de datos.

[Video de apoyo a la lectura experimental hasta aquí](https://youtu.be/Z-V1lNZ1iyc)

# Implementemos ahora la clase  

Aquí tienes un diseño de clase sobre la estructura de datos `DataFrame` en Pandas para su aplicación en ciencia de datos y técnicas de machine learning.

---


### 1. Título de la Clase
**Introducción a DataFrames en Pandas y su Aplicación en Ciencia de Datos y Machine Learning**


### 2. Objetivo de Aprendizaje

Al finalizar esta clase, los estudiantes serán capaces de:

- Crear y manipular DataFrames en Pandas.

- Explorar y limpiar datos utilizando métodos de Pandas.
- Aplicar operaciones comunes de ciencia de datos en DataFrames para la preparación de datos en proyectos de machine learning.


### 3. Contenido de la Clase

1. **Introducción a Pandas y a la Estructura de Datos `DataFrame`**
   - ¿Qué es Pandas y por qué es fundamental en ciencia de datos?
   - Definición y características de un `DataFrame`.
   - Comparación de `DataFrame` con otras estructuras de datos (listas, nd-arrays).

Aquí tienes el desarrollo de la primera parte del contenido para la clase sobre la estructura `DataFrame` en Pandas:

---


### 1. **Introducción a Pandas y a la Estructura de Datos `DataFrame`**


#### ¿Qué es Pandas y por qué es fundamental en ciencia de datos?

Pandas es una biblioteca de Python diseñada específicamente para el manejo y análisis de datos.

Proporciona estructuras de datos y herramientas de alto rendimiento para trabajar con datos de una forma flexible y eficiente, facilitando tareas como la limpieza, manipulación, y análisis de grandes volúmenes de datos. En ciencia de datos, Pandas es esencial porque:


- **Permite manipular y limpiar datos** de manera sencilla y eficaz, preparando conjuntos de datos para el análisis.
- **Facilita el trabajo con datos tabulares** (similares a los que se encuentran en hojas de cálculo y bases de datos).
- **Ofrece una gran cantidad de funciones y métodos** para filtrar, transformar y agrupar datos, lo que permite realizar análisis complejos de forma rápida.
- **Soporta la integración con otras bibliotecas** populares de Python, como NumPy, Matplotlib y scikit-learn, lo que es especialmente útil para aplicaciones de machine learning.


#### Definición y características de un `DataFrame`
Un `DataFrame` es una estructura de datos bidimensional de Pandas, similar a una tabla de una hoja de cálculo o una base de datos relacional. Está compuesta por filas y columnas, donde:

- **Las filas representan observaciones o registros**, y cada fila contiene datos de diferentes variables.
- **Las columnas representan variables o atributos**, y cada columna tiene un nombre único que permite su identificación.

Características principales de un `DataFrame`:


1. **Estructura etiquetada**: Las filas y columnas tienen etiquetas, lo que permite el acceso rápido a los datos.
2. **Soporte para múltiples tipos de datos**: Cada columna puede contener diferentes tipos de datos (números, texto, fechas, etc.).
3. **Operaciones optimizadas**: Pandas aprovecha la biblioteca NumPy para hacer las operaciones más eficientes, lo que permite realizar cálculos y transformaciones rápidamente.
4. **Manejo de datos faltantes**: Los `DataFrames` ofrecen herramientas para identificar y manejar valores nulos o faltantes, un aspecto fundamental en el análisis de datos.


#### Comparación de `DataFrame` con otras estructuras de datos (listas, nd-arrays)
Para entender mejor el poder y la flexibilidad de los `DataFrames`, es útil compararlos con otras estructuras de datos en Python:


- **Listas**:
  - **Flexibilidad**: Las listas pueden contener diferentes tipos de datos, pero carecen de estructura tabular.
  - **Limitaciones**: No están diseñadas para el manejo de datos tabulares ni cuentan con funciones para operaciones complejas como agrupaciones o filtrado por condiciones.

In [3]:
lista = [1,2,3, 5.6, True, 'marco']
lista

[1, 2, 3, 5.6, True, 'marco']

In [4]:
lista.ndim

AttributeError: 'list' object has no attribute 'ndim'


- **`nd-arrays` de NumPy**:

  - **Homogeneidad**: Los `nd-arrays` son más rápidos que las listas y pueden manejar grandes cantidades de datos, pero solo permiten un tipo de datos en cada array.
  - **Limitaciones**: No incluyen etiquetas para las filas y columnas, lo que dificulta el análisis cuando se requiere acceder a datos específicos por nombres de columna. También carecen de herramientas integradas para manipulación de datos faltantes y para la integración de datos heterogéneos.

In [14]:
import numpy as np 

matriz = np.array([[1,4.3,True]])
columna = np.array([[1], [2]])

In [16]:
matriz.dtype

dtype('float64')

In [6]:
matriz.ndim

2


- **`DataFrames` de Pandas**:
  - **Flexibilidad y etiquetas**: Combina las ventajas de las listas y `nd-arrays` y añade etiquetas tanto en filas como en columnas, lo que facilita un acceso y manipulación intuitiva de los datos.
  - **Soporte para tipos de datos heterogéneos**: Los `DataFrames` permiten trabajar con diferentes tipos de datos en distintas columnas, lo que es fundamental para el análisis de datos del mundo real.
  - **Funcionalidades avanzadas**: Integran métodos especializados para limpieza, agrupación, y análisis, lo que los hace ideales para ciencia de datos.

In [12]:
import pandas as pd 

df = pd.DataFrame({'nombre': 'Marco', 'edad': 49}, index = [1]) 
df

  nombre  edad
1  Marco    49


Con estas características, los `DataFrames` se destacan como la estructura de datos preferida en proyectos de ciencia de datos, facilitando el flujo de trabajo desde la limpieza de datos hasta el modelado en machine learning.

[Video de apoyo a la lectura experimental hasta aquí]()


2. **Creación de DataFrames**
   - Creación de `DataFrames` a partir de listas, diccionarios, y archivos (CSV, Excel).
   - Exploración de datos con funciones como `head()`, `tail()`, `info()`, y `describe()`.

Nos enfocaremos en crear `DataFrames` a partir de distintas fuentes y en explorar sus datos con funciones esenciales de Pandas.

Este enfoque es ideal para comprender cómo trabajar con conjuntos de datos en un contexto real.

---


### 1. **Creación de DataFrames**

#### 1.1. Crear un DataFrame a partir de Listas
Podemos crear un `DataFrame` usando listas en Python. Esto es útil cuando queremos estructurar datos de manera sencilla.

In [ ]:
import pandas as pd

# Creación de un DataFrame a partir de una lista de listas
datos = [[1, 'Carlos', 25],
         [2, 'Ana', 30],
         [3, 'Pedro', 35]]

columnas = ['ID', 'Nombre', 'Edad']  

indices = ['primero', 'segundo', 'tercero']  

df_listas = pd.DataFrame(datos, columns=columnas, index = indices) 
df_listas

TypeError: Cannot convert numpy.ndarray to numpy.ndarray

In [20]:
df_listas.set_index('ID', inplace=True)

In [21]:
df_listas

    Nombre  Edad
ID
1   Carlos    25
2      Ana    30
3    Pedro    35


#### 1.2. Crear un DataFrame a partir de Diccionarios

Otra forma común de crear `DataFrames` es a partir de diccionarios.

Este método nos permite asignar valores directamente a columnas con nombres específicos.

In [ ]:
# Creación de un DataFrame a partir de un diccionario
import pandas as pd 
datos_dict = {
    'ID': [1, 2, 3],
    'Nombre': ['Carlos', 'Ana', 'Pedro'],
    'Edad': [25, 30, 35]
}

df_diccionario = pd.DataFrame(datos_dict)
df_diccionario

   ID  Nombre  Edad
0   1  Carlos    25
1   2     Ana    30
2   3   Pedro    35

In [25]:
df_diccionario.set_index('ID' , inplace=True)

In [26]:
df_diccionario

    Nombre  Edad
ID
1   Carlos    25
2      Ana    30
3    Pedro    35


#### 1.3. Crear un DataFrame a partir de un Archivo (CSV)

En la práctica, muchas veces trabajaremos con archivos de datos. Pandas facilita la importación de archivos CSV.

In [32]:
df_diccionario.to_csv('ejemplo_datos.csv', index = True)

In [33]:
# Cargar un archivo CSV en un DataFrame
df_csv = pd.read_csv('ejemplo_datos.csv')
df_csv

   ID  Nombre  Edad
0   1  Carlos    25
1   2     Ana    30
2   3   Pedro    35


#### 1.4. Crear un DataFrame a partir de un Archivo de Excel
Además de CSV, también se pueden leer archivos de Excel. Para esto, asegúrate de tener instalado el módulo `openpyxl`.

In [35]:
df_diccionario.to_excel('ejemplo_datos_excel.xlsx')

In [2]:
# Cargar un archivo de Excel en un DataFrame
import pandas as pd 
df_excel = pd.read_excel('ejemplo_datos_excel.xlsx')
df_excel

   ID  Nombre  Edad
0   1  Carlos    25
1   2     Ana    30
2   3   Pedro    35


### 2. **Exploración de Datos en DataFrames**

Una vez creado el `DataFrame`, es importante familiarizarse con su estructura y contenido.

Pandas ofrece varias funciones para explorar rápidamente los datos.


#### 2.1. `head()` y `tail()`
Estas funciones son útiles para ver las primeras y últimas filas del `DataFrame`.

In [4]:


# Ver las primeras 5 filas del DataFrame
df_excel.head()

   ID  Nombre  Edad
0   1  Carlos    25
1   2     Ana    30
2   3   Pedro    35

In [5]:

# Ver las últimas 5 filas del DataFrame
df_excel.tail(2)

   ID Nombre  Edad
1   2    Ana    30
2   3  Pedro    35


Puedes ajustar el número de filas mostradas con un parámetro, por ejemplo, `df_csv.head(10)` mostrará las primeras 10 filas.


#### 2.2. `info()`
`info()` proporciona un resumen de los datos, incluyendo el tipo de cada columna, el número de valores no nulos y la memoria usada.

In [6]:
# Información general del DataFrame
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      3 non-null      int64
 1   Nombre  3 non-null      object
 2   Edad    3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes


#### 2.3. `describe()`
Para analizar datos numéricos, `describe()` ofrece estadísticas como la media, desviación estándar, valores mínimo y máximo, y percentiles.

In [7]:

# Estadísticas descriptivas de columnas numéricas
df_excel.describe()

        ID  Edad
count  3.0   3.0
mean   2.0  30.0
std    1.0   5.0
min    1.0  25.0
25%    1.5  27.5
50%    2.0  30.0
75%    2.5  32.5
max    3.0  35.0

``

---


### Ejercicio Propuesto

**Crear un DataFrame a partir de un archivo CSV y explorar sus datos.**

1. Descarga un archivo CSV de tu elección. Puedes encontrar conjuntos de datos gratuitos en [Kaggle](https://www.kaggle.com/datasets) o [datos.gov.co](https://www.datos.gov.co/).
2. Crea un `DataFrame` a partir del archivo.
3. Utiliza `head()`, `tail()`, `info()`, y `describe()` para explorar el contenido del `DataFrame`.

In [9]:


# Solución del ejercicio
# Supongamos que tienes un archivo llamado 'datos_ejemplo.csv'
df_ejemplo = pd.read_csv('C:/Users/marco/Documentos/docencia/ideam/presion_ideam/Presi_n_Atmosf_rica.csv')

# Explora el DataFrame
df_ejemplo.head()

,CodigoEstacion,CodigoSensor,FechaObservacion,ValorObservado,NombreEstacion,Departamento,Municipio,ZonaHidrografica,Latitud,Longitud,DescripcionSensor,UnidadMedida
0,36015020,255,10/03/2017 06:00:00 AM,992.5,EL DIAMANTE - AUT,CASANARE,PAZ DE ARIPORO,META,5.816194,-71.419833,Presión Atmosferica (1h),HPa
1,21195190,255,02/14/2014 05:00:00 AM,785.2,PASCA - AUT,CUNDINAMARCA,PASCA,ALTO MAGDALENA,4.310111,-74.311750,Presión Atmosferica (1h),HPa
2,21015050,255,09/27/2013 06:00:00 PM,805.3,PURACE - AUT,HUILA,SAN AGUSTÍN,ALTO MAGDALENA,1.925917,-76.427556,Presión Atmosferica (1h),HPa
3,21115010,255,11/28/2005 10:00:00 AM,958.5,DESIERTO TATACOA,HUILA,VILLAVIEJA,ALTO MAGDALENA,3.234000,-75.168000,Presión Atmosferica (1h),HPa
4,28035060,255,04/08/2008 04:00:00 AM,988.7,FEDEARROZ - AUT,CESAR,VALLEDUPAR,CESAR,10.463611,-73.248056,Presión Atmosferica (1h),HPa

In [10]:
df_ejemplo.tail()

,CodigoEstacion,CodigoSensor,FechaObservacion,ValorObservado,NombreEstacion,Departamento,Municipio,ZonaHidrografica,Latitud,Longitud,DescripcionSensor,UnidadMedida
24108971,17015010,258,12/03/2024 12:00:00 PM,"1,012.9",AEROPUERTO SESQUICENTENARIO,ARCHIPIELAGO DE SAN ANDRES PROVIDENCIA Y SANTA...,SAN ANDRÉS,ISLAS CARIBE,12.587849,-81.701117,GPRS - PRESIÓN ATMOSFÉRICA,hPA
24108972,29045190,258,12/03/2024 11:38:00 AM,"1,006.7",AEROPUERTO E. CORTISSOZ,ATLANTICO,SOLEDAD,BAJO MAGDALENA,10.917778,-74.779722,GPRS - PRESIÓN ATMOSFÉRICA,hPA
24108973,25010010,255,12/03/2024 10:00:00 PM,996.2,PUERTO LIBERTADOR,CORDOBA,PUERTO LIBERTADOR,BAJO MAGDALENA- CAUCA -SAN JORGE,7.890278,-75.680000,PRESIÓN ATMOSFÉRICA,hPa
24108974,11175000,255,12/03/2024 07:00:00 AM,"1,008.4",ATRATO,CHOCO,CÉRTEGUI,ATRATO - DARIÉN,5.585776,-76.649978,PRESIÓN ATMOSFÉRICA,hPa
24108975,17015010,258,12/03/2024 12:44:00 PM,"1,013.7",AEROPUERTO SESQUICENTENARIO,ARCHIPIELAGO DE SAN ANDRES PROVIDENCIA Y SANTA...,SAN ANDRÉS,ISLAS CARIBE,12.587849,-81.701117,GPRS - PRESIÓN ATMOSFÉRICA,hPA

In [11]:
df_ejemplo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24108976 entries, 0 to 24108975
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   CodigoEstacion     int64
 1   CodigoSensor       int64
 2   FechaObservacion   object
 3   ValorObservado     object
 4   NombreEstacion     object
 5   Departamento       object
 6   Municipio          object
 7   ZonaHidrografica   object
 8   Latitud            float64
 9   Longitud           float64
 10  DescripcionSensor  object
 11  UnidadMedida       object
dtypes: float64(2), int64(2), object(8)
memory usage: 2.2+ GB

In [12]:
df_ejemplo.describe().round(2)

       CodigoEstacion  CodigoSensor      Latitud     Longitud
count    2.410898e+07   24108976.00  24108976.00  24108976.00
mean     2.075885e+08        255.55         5.54       -74.58
std      7.016728e+08          1.16         3.39         2.20
min      1.103001e+07        255.00        -4.19       -81.73
25%      2.120552e+07        255.00         4.37       -75.74
50%      2.405507e+07        255.00         5.08       -74.28
75%      3.507507e+07        255.00         7.19       -73.40
max      5.311500e+09        258.00        15.80         0.00

In [14]:
df_ejemplo.rename(columns={'ValorObservado':'PresionAtmosferica'}, inplace=True)

In [15]:
df_ejemplo.head()

,CodigoEstacion,CodigoSensor,FechaObservacion,PresionAtmosferica,NombreEstacion,Departamento,Municipio,ZonaHidrografica,Latitud,Longitud,DescripcionSensor,UnidadMedida
0,36015020,255,10/03/2017 06:00:00 AM,992.5,EL DIAMANTE - AUT,CASANARE,PAZ DE ARIPORO,META,5.816194,-71.419833,Presión Atmosferica (1h),HPa
1,21195190,255,02/14/2014 05:00:00 AM,785.2,PASCA - AUT,CUNDINAMARCA,PASCA,ALTO MAGDALENA,4.310111,-74.311750,Presión Atmosferica (1h),HPa
2,21015050,255,09/27/2013 06:00:00 PM,805.3,PURACE - AUT,HUILA,SAN AGUSTÍN,ALTO MAGDALENA,1.925917,-76.427556,Presión Atmosferica (1h),HPa
3,21115010,255,11/28/2005 10:00:00 AM,958.5,DESIERTO TATACOA,HUILA,VILLAVIEJA,ALTO MAGDALENA,3.234000,-75.168000,Presión Atmosferica (1h),HPa
4,28035060,255,04/08/2008 04:00:00 AM,988.7,FEDEARROZ - AUT,CESAR,VALLEDUPAR,CESAR,10.463611,-73.248056,Presión Atmosferica (1h),HPa

In [18]:
import numpy as np 
# Reemplazar comas por puntos
df_ejemplo['PresionAtmosferica'] = df_ejemplo['PresionAtmosferica'].str.replace(',', '')

df_ejemplo.PresionAtmosferica.astype(np.float64)

0            992.5
1            785.2
2            805.3
3            958.5
4            988.7
             ...
24108971    1012.9
24108972    1006.7
24108973     996.2
24108974    1008.4
24108975    1013.7
Name: PresionAtmosferica, Length: 24108976, dtype: float64


---

### Conclusión

Crear y explorar `DataFrames` es un paso inicial crucial en el análisis de datos.

En esta clase aprendiste a crear `DataFrames` a partir de listas, diccionarios y archivos comunes (CSV y Excel) y a explorar su contenido. Familiarizarse con estas técnicas es esencial para proyectos de análisis de datos y para trabajar de manera eficiente en Python.


En la siguiente clase, podríamos abordar la **manipulación y limpieza de datos en `DataFrames`**, algo que resulta fundamental para obtener datos de calidad para análisis posteriores.

[Video de apoyo hasta aquí: creacion dataframe](https://www.youtube.com/watch?v=eYlIfj8xwaA)


3. **Manipulación de Datos en un DataFrame**
   - Selección y filtrado de datos: acceso a filas y columnas.
   - Modificación de valores, creación y eliminación de columnas.
   - Manejo de valores nulos y duplicados.

Aquí tienes la tercera parte de la clase sobre `DataFrames` en Pandas, enfocada en la manipulación de datos. Este contenido te ayudará a trabajar de manera más avanzada con datos en un `DataFrame`, realizando tareas comunes como seleccionar y filtrar datos, modificar valores, crear y eliminar columnas, y manejar valores nulos y duplicados.

---


### Clase 3: Manipulación de Datos en un DataFrame de Pandas


### Objetivo
- Aprender a seleccionar y filtrar datos en un `DataFrame`.
- Modificar valores, crear y eliminar columnas.
- Manejar valores nulos y duplicados en los datos.

---


### 1. **Selección y Filtrado de Datos**

#### 1.1 Selección de Columnas
Puedes seleccionar una o varias columnas de un `DataFrame` utilizando el nombre de la columna entre corchetes `[]`.

In [23]:


import pandas as pd

# Ejemplo de DataFrame
data = {
    'ID': [1, 2, 3, 4, 5],
    'Nombre': ['Carlos', 'Ana', 'Pedro', 'Maria', 'Luis'],
    'Edad': [25, 30, 35, 28, 22],
    'Ciudad': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena']
}

In [6]:
data

{'ID': [1, 2, 3, 4, 5],
 'Nombre': ['Carlos', 'Ana', 'Pedro', 'Maria', 'Luis'],
 'Edad': [25, 30, 35, 28, 22],
 'Ciudad': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena']}

In [7]:
df = pd.DataFrame(data)
df

   ID  Nombre  Edad        Ciudad
0   1  Carlos    25        Bogotá
1   2     Ana    30      Medellín
2   3   Pedro    35          Cali
3   4   Maria    28  Barranquilla
4   5    Luis    22     Cartagena

In [8]:

# Selección de una columna con notación de corchetes 
df[['Nombre', 'Edad']]

   Nombre  Edad
0  Carlos    25
1     Ana    30
2   Pedro    35
3   Maria    28
4    Luis    22

In [9]:
df[['Edad', 'Nombre']]

   Edad  Nombre
0    25  Carlos
1    30     Ana
2    35   Pedro
3    28   Maria
4    22    Luis

In [10]:
df.Nombre  # Con notación de punto

0    Carlos
1       Ana
2     Pedro
3     Maria
4      Luis
Name: Nombre, dtype: object

In [11]:

# Selección de múltiples columnas
df[['Nombre', 'Edad']]

   Nombre  Edad
0  Carlos    25
1     Ana    30
2   Pedro    35
3   Maria    28
4    Luis    22


#### 1.2 Selección de Filas
Puedes seleccionar filas de varias maneras:

- **Índices de Filas** con `.iloc` (por posición) o `.loc` (por etiqueta).

In [12]:
datos = [['Marco', 49], ['Joseph', 16]]
indices = ['Padre', 'Hijo']
columnas = ['Nombre', 'Edad']

df = pd.DataFrame(datos, index=indices, columns=columnas)
df

       Nombre  Edad
Padre   Marco    49
Hijo   Joseph    16

In [13]:
df.iloc[0]

Nombre    Marco
Edad         49
Name: Padre, dtype: object

In [14]:
df.loc['Padre']

Nombre    Marco
Edad         49
Name: Padre, dtype: object

In [15]:

# Selección de la primera fila con iloc
df.iloc[0]

Nombre    Marco
Edad         49
Name: Padre, dtype: object

In [18]:

# Selección de una fila por índice con loc
# df.loc[2]


#### 1.3 Filtrado de Datos
El filtrado de datos permite seleccionar solo aquellas filas que cumplen con ciertas condiciones.

In [19]:
booleano = df['Edad'] < 25  # operador de comparación

In [20]:
df[booleano] # Evaluar el dataframe en la serie de booleanos

      Nombre  Edad
Hijo  Joseph    16

In [21]:


# Filtrar filas donde Edad es mayor a 25
df_mayores_25 = df[df['Edad'] > 25]
df_mayores_25

      Nombre  Edad
Padre  Marco    49

In [25]:

# Filtrar filas donde Ciudad es 'Medellín'
# df_medellin = df[(df['Ciudad'] == 'Medellín') & (df['Edad'] > 20)] # no olvide los signos de agrupeción
# df_medellin


### 2. **Modificación de Valores, Creación y Eliminación de Columnas**

#### 2.1 Modificación de Valores
Puedes modificar los valores de una columna seleccionándola y aplicando cambios.

In [26]:
df.loc[df['Nombre']=='Carlos','Edad'] = 27  # Operador de asignación modificar

In [26]:
df

   ID  Nombre  Edad        Ciudad
0   1  Carlos    27        Bogotá
1   2     Ana    30      Medellín
2   3   Pedro    35          Cali
3   4   Maria    28  Barranquilla
4   5    Luis    22     Cartagena

* El método .loc tiene dos parámetros. 
* Con solo un parámetro en va a la fila 
* Con los dos parámetros en va a la fila y columna respectiva.

In [27]:


# Cambiar la edad de Carlos a 26
df.loc[df['Nombre'] == 'Carlos', 'Edad'] = 26
df

       Nombre  Edad
Padre   Marco    49
Hijo   Joseph    16


#### 2.2 Creación de Nuevas Columnas
Para añadir una columna nueva, solo tienes que asignar valores a un nombre de columna que aún no exista.

In [29]:

# Crear una nueva columna llamada 'Salario' con valores predeterminados
# df['Salario'] = [3000, 4000, 5000, 3500, 2800]
df

       Nombre  Edad
Padre   Marco    49
Hijo   Joseph    16


#### 2.3 Eliminación de Columnas
Para eliminar columnas, utiliza la función `drop()`, especificando `axis=1` para indicar que quieres eliminar columnas (en vez de filas).

In [30]:
# df.drop(['ID', 'Nombre'], axis = 1, inplace=True)  # No olvidar el párámetro axis

In [53]:
df

   index  Edad        Ciudad
0      0  27.0        Bogotá
1      1  35.0          Cali
2      2  28.0  Barranquilla
3      3  22.0     Cartagena

In [31]:

# Eliminar la columna 'Salario'
#df = df.drop('Salario', axis=1)
df

       Nombre  Edad
Padre   Marco    49
Hijo   Joseph    16


### 3. **Manejo de Valores Nulos y Duplicados**

#### 3.1 Manejo de Valores Nulos
A veces, los `DataFrames` contienen valores nulos (`NaN`). Es importante saber cómo identificarlos y manejarlos.

- **Identificación de valores nulos**: Usa `isnull()` o `notnull()` para identificar valores nulos.

In [55]:
df

   index  Edad        Ciudad
0      0  27.0        Bogotá
1      1  35.0          Cali
2      2  28.0  Barranquilla
3      3  22.0     Cartagena

In [56]:

# Crear algunos valores nulos en el DataFrame
df.loc[1, 'Edad'] = None
df

   index  Edad        Ciudad
0      0  27.0        Bogotá
1      1   NaN          Cali
2      2  28.0  Barranquilla
3      3  22.0     Cartagena

In [34]:

# Verificar si hay valores nulos
df.isnull() # esto genera un dataframe de valores booleanos donde True indica un valor nulo

       Nombre   Edad
Padre   False  False
Hijo    False  False

In [33]:
df.notnull()

       Nombre  Edad
Padre    True  True
Hijo     True  True


- **Eliminar valores nulos**: Usa `dropna()` para eliminar filas o columnas con valores nulos.

In [32]:

# Eliminar filas con valores nulos
df.dropna(subset = ['Edad'], inplace= True)
df

       Nombre  Edad
Padre   Marco    49
Hijo   Joseph    16

In [60]:
df.reset_index( drop = True, inplace=True) # Reset the index to get a clean DataFrame
df

   index  Edad        Ciudad
0      0  27.0        Bogotá
1      2  28.0  Barranquilla
2      3  22.0     Cartagena


- **Rellenar valores nulos**: Usa `fillna()` para reemplazar valores nulos con un valor específico.

In [ ]:


# Rellenar valores nulos en 'Edad' con el valor promedio de la columna
df['Edad'] = df['Edad'].fillna(df['Edad'].mean())
df


#### 3.2 Manejo de Datos Duplicados
Es posible que en un `DataFrame` haya filas duplicadas. Pandas proporciona herramientas para identificarlas y eliminarlas.

- **Identificar duplicados**: Usa `duplicated()` para ver qué filas están duplicadas.

In [61]:


import pandas as pd

# Ejemplo de DataFrame
data = {
    'ID': [1, 2, 3, 4, 5],
    'Nombre': ['Carlos', 'Ana', 'Pedro', 'Maria', 'Luis'],
    'Edad': [25, 30, 35, 28, 22],
    'Ciudad': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena']
}
df = pd.DataFrame(data)
df

   ID  Nombre  Edad        Ciudad
0   1  Carlos    25        Bogotá
1   2     Ana    30      Medellín
2   3   Pedro    35          Cali
3   4   Maria    28  Barranquilla
4   5    Luis    22     Cartagena

In [65]:
fila_nueva = df.iloc[[-1]]

In [68]:
df, fila_nueva

(   ID  Nombre  Edad        Ciudad
 0   1  Carlos    25        Bogotá
 1   2     Ana    30      Medellín
 2   3   Pedro    35          Cali
 3   4   Maria    28  Barranquilla
 4   5    Luis    22     Cartagena,
    ID Nombre  Edad     Ciudad
 4   5   Luis    22  Cartagena)

In [73]:
pd.concat([df, fila_nueva], axis = 0, ignore_index=True)

   ID  Nombre  Edad        Ciudad
0   1  Carlos    25        Bogotá
1   2     Ana    30      Medellín
2   3   Pedro    35          Cali
3   4   Maria    28  Barranquilla
4   5    Luis    22     Cartagena
5   5    Luis    22     Cartagena

In [ ]:
fila_nueva = df.iloc[[-1]] # doble corchete para mantener la estructura de dataframa 
df = pd.concat([df, fila_nueva], ignore_index=True)
df


- **Eliminar duplicados**: Usa `drop_duplicates()` para eliminar filas duplicadas.

In [74]:

# Eliminar filas duplicadas
df_sin_duplicados = df.drop_duplicates()
df_sin_duplicados

   ID  Nombre  Edad        Ciudad
0   1  Carlos    25        Bogotá
1   2     Ana    30      Medellín
2   3   Pedro    35          Cali
3   4   Maria    28  Barranquilla
4   5    Luis    22     Cartagena

In [ ]:
df


---


### Ejercicio Propuesto

1. **Crear y Modificar un DataFrame**: Crea un `DataFrame` de ejemplo con los datos de estudiantes (ID, Nombre, Edad, Carrera).
2. **Filtrar Datos**: Selecciona solo los estudiantes mayores de 20 años.
3. **Añadir y Eliminar Columnas**: Agrega una columna con los promedios de los estudiantes y luego elimínala.
4. **Manejo de Valores Nulos y Duplicados**: Introduce un valor nulo en una columna, rellénalo con un valor predeterminado y luego elimina las filas duplicadas en el `DataFrame`.


---

### Conclusión

La manipulación de datos en Pandas te permite seleccionar, modificar, y limpiar datos de manera flexible y eficiente. En esta clase aprendiste a seleccionar y filtrar datos, a crear y eliminar columnas, y a manejar valores nulos y duplicados, que son habilidades fundamentales para el análisis de datos.

Para la siguiente clase, podríamos enfocarnos en **agrupar y resumir datos**, lo que te ayudará a realizar análisis más avanzados en tus `DataFrames`.

[Video de apoyo a la lectura hasta aquí](https://www.youtube.com/watch?v=hdtipduaggo)


4. **Operaciones de Limpieza y Transformación de Datos**
   - Métodos para limpiar datos y eliminar registros incompletos.
   - Transformación de tipos de datos.
   - Uso de funciones como `apply()`, `groupby()`, y `merge()`.

Aquí tienes la cuarta parte de la clase sobre la estructura de datos `DataFrame` con el contenido de **Operaciones de Limpieza y Transformación de Datos**:

---


## 4. **Operaciones de Limpieza y Transformación de Datos**


La limpieza y transformación de datos son pasos esenciales cuando trabajamos con `DataFrames` en `pandas`.

Estas operaciones permiten preparar los datos para análisis más precisos y robustos. En esta sección, aprenderemos a limpiar, transformar, y manipular los datos utilizando métodos clave de `pandas`.


### 4.1 Métodos para Limpiar Datos y Eliminar Registros Incompletos


La limpieza de datos implica manejar valores nulos o duplicados y eliminar registros que no cumplen con ciertos criterios.

- **Eliminar valores nulos**: Podemos usar `.dropna()` para eliminar filas o columnas con valores nulos.

In [36]:
import pandas as pd

In [35]:

df = pd.DataFrame({
      'A': [1, 1, 3, 4, 3],
      'B': [None, 2, None, 5, 2]
  })

df

   A    B
0  1  NaN
1  1  2.0
2  3  NaN
3  4  5.0
4  3  2.0

In [37]:

  # Eliminar filas con valores nulos
df_sin_filas_nulos = df.dropna()
df_sin_filas_nulos

   A    B
1  1  2.0
3  4  5.0
4  3  2.0

In [38]:

  # Eliminar columnas con valores nulos
df_sin_nulos_columnas = df.dropna(axis=1)
df_sin_nulos_columnas

   A
0  1
1  1
2  3
3  4
4  3


- **Rellenar valores nulos**: Utilizamos `.fillna()` para reemplazar los valores nulos con un valor específico, como la media, mediana, o un valor constante.

In [39]:
df_rellenado = df.fillna(0)  # Rellenar valores nulos con 0

df_rellenado

   A    B
0  1  0.0
1  1  2.0
2  3  0.0
3  4  5.0
4  3  2.0


- **Eliminar duplicados**: `.drop_duplicates()` elimina las filas duplicadas en el `DataFrame`.

In [6]:
df_sin_duplicados = df.drop_duplicates()

df_sin_duplicados

     A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  NaN
3  4.0  5.0


### 4.2 Transformación de Tipos de Datos

En ocasiones, es necesario transformar los tipos de datos de las columnas para facilitar cálculos y análisis.

Por ejemplo, convertir datos de texto a numéricos o fechas.

- **Convertir a otro tipo de datos**: Para cambiar el tipo de datos de una columna, usamos `.astype()`.

In [40]:
df_rellenado = df.fillna(0)
df_rellenado['A'] = df_rellenado['A'].astype(int)  # Convertir la columna 'A' a tipo float
df_rellenado

   A    B
0  1  0.0
1  1  2.0
2  3  0.0
3  4  5.0
4  3  2.0

In [41]:
df

   A    B
0  1  NaN
1  1  2.0
2  3  NaN
3  4  5.0
4  3  2.0


- **Convertir cadenas a fechas**: Si tenemos fechas en formato de texto, podemos convertirlas a tipo `datetime` con `pd.to_datetime()`.

In [44]:
df['Fecha'] = ['12/11/2024', '13/11/2024', '14/11/2024', '15/11/2024', '16/11/2024']
df

   A    B       fecha       Fecha
0  1  NaN  12/11/2024  12/11/2024
1  1  2.0  13/11/2024  13/11/2024
2  3  NaN  14/11/2024  14/11/2024
3  4  5.0  15/11/2024  15/11/2024
4  3  2.0  16/11/2024  16/11/2024

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       3 non-null      float64
 2   fecha   5 non-null      object
 3   Fecha   5 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [46]:

df['fecha'] = pd.to_datetime(df['fecha'], format = '%d/%m/%Y')

df

   A    B      fecha       Fecha
0  1  NaN 2024-11-12  12/11/2024
1  1  2.0 2024-11-13  13/11/2024
2  3  NaN 2024-11-14  14/11/2024
3  4  5.0 2024-11-15  15/11/2024
4  3  2.0 2024-11-16  16/11/2024

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       3 non-null      float64
 2   fecha   5 non-null      datetime64[ns]
 3   Fecha   5 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 292.0+ bytes


### 4.3 Uso de Funciones como `apply()`, `groupby()`, y `merge()`

Estas funciones permiten realizar operaciones avanzadas y manipulación de datos en un `DataFrame`.


- **`apply()`**: Permite aplicar una función a cada elemento de una columna o fila. Es muy útil para realizar transformaciones personalizadas.

In [ ]:
 # Aplicar una función para incrementar cada valor de la columna 'A' en 10
df['A'] = df['A'].apply(lambda x: x + 10)

In [22]:

df

      A    B      fecha
0  11.0  NaN 2024-11-12
1   NaN  2.0 2024-11-13
2  13.0  NaN 2024-11-14
3  14.0  5.0 2024-11-15


- **`groupby()`**: Agrupa los datos según una columna y permite realizar cálculos agregados, como `sum()`, `mean()`, etc.

In [27]:
df

   A    B
0  1  NaN
1  1  2.0
2  3  NaN
3  4  5.0
4  3  2.0

In [26]:
# Agrupar por la columna 'B' y calcular la suma de 'A' en cada grupo
df_agrupado = df.groupby('B')['A'].sum()
df_agrupado

B
2.0    4
5.0    4
Name: A, dtype: int64


- **`merge()`**: Combina dos `DataFrames` en uno solo, similar a una unión en bases de datos.

Es útil cuando se tienen conjuntos de datos separados que necesitan integrarse.

In [28]:
df1 = pd.DataFrame({'ID': [1, 2], 'Valor': ['A', 'B']})
df2 = pd.DataFrame({'ID': [1, 2], 'Cantidad': [10, 20]})

# Combinar los DataFrames en una sola tabla
df_combinado = pd.merge(df1, df2, on='ID')

df_combinado

   ID Valor  Cantidad
0   1     A        10
1   2     B        20


### Resumen


Las operaciones de limpieza y transformación de datos en `pandas` son cruciales para el análisis de datos, permitiéndonos preparar los datos y mejorar su calidad.

Los métodos `apply()`, `groupby()`, y `merge()` son especialmente útiles para realizar cálculos personalizados, agrupar y combinar datos.

---


Este contenido abarca los aspectos clave en la limpieza y transformación de datos con `DataFrame`, cubriendo los métodos y funciones esenciales de `pandas`.

[Video de apoyo hasta aquí](https://www.youtube.com/watch?v=_xeaOVq0Qqs)


5. **Preparación de Datos para Machine Learning**
   - Normalización y estandarización de datos numéricos.
   - Codificación de variables categóricas.
   - División de los datos en conjuntos de entrenamiento y prueba.

Esta es la quinta parte de una clase sobre la estructura de datos `DataFrame` de pandas enfocada en la preparación de datos para Machine Learning.

Este contenido cubre la normalización y estandarización de datos numéricos, la codificación de variables categóricas y la división de datos en conjuntos de entrenamiento y prueba.

---


### 5. **Preparación de Datos para Machine Learning**

Al trabajar con modelos de Machine Learning, la calidad y estructura de los datos son esenciales para obtener buenos resultados. Pandas proporciona funciones que ayudan a preprocesar los datos, adaptándolos al formato y escala que los modelos necesitan. En esta sección, abordaremos tres pasos clave en el preprocesamiento de datos para Machine Learning.

---


#### 5.1 **Normalización y Estandarización de Datos Numéricos**

La normalización y la estandarización son técnicas comunes para escalar los datos, lo cual es crucial cuando se trabaja con algoritmos de Machine Learning que son sensibles a las escalas de las variables, como los modelos basados en distancias (ej., K-Nearest Neighbors) y redes neuronales.

1. **Normalización**: La normalización reescala los valores de las variables numéricas para que se encuentren dentro de un rango específico, generalmente entre 0 y 1. Esto se hace restando el valor mínimo y dividiendo entre el rango de los datos.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Aplicar normalización
scaler = MinMaxScaler()
df[['columna1', 'columna2']] = scaler.fit_transform(df[['columna1', 'columna2']])


2. **Estandarización**: La estandarización reescala los datos de manera que tengan una media de 0 y una desviación estándar de 1. Es útil cuando los datos tienen distribuciones normales y cuando las escalas originales de las variables son muy diferentes.

In [ ]:
from sklearn.preprocessing import StandardScaler

   # Aplicar estandarización
scaler = StandardScaler()
df[['columna1', 'columna2']] = scaler.fit_transform(df[['columna1', 'columna2']])


---

#### 5.2 **Codificación de Variables Categóricas**

Los algoritmos de Machine Learning necesitan que las variables categóricas se transformen en un formato numérico. Existen dos métodos comunes:

1. **Codificación One-Hot**: Crea una columna para cada categoría con valores 0 o 1, indicando la presencia de una categoría específica. Este método es útil para variables categóricas sin orden inherente.

In [ ]:

# Codificación One-Hot
df = pd.get_dummies(df, columns=['columna_categorica'])


2. **Codificación Label Encoding**: Asigna un número entero único a cada categoría. Este método es adecuado para variables con un orden implícito, aunque hay que tener cuidado, ya que los modelos pueden interpretar el orden como significativo.

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Codificación Label Encoding
encoder = LabelEncoder()
df['columna_categorica'] = encoder.fit_transform(df['columna_categorica'])


---

#### 5.3 **División de los Datos en Conjuntos de Entrenamiento y Prueba**

Para evaluar el rendimiento de los modelos de Machine Learning, es fundamental dividir el conjunto de datos en dos subconjuntos:

- **Conjunto de Entrenamiento**: Utilizado para ajustar el modelo.
- **Conjunto de Prueba**: Utilizado para evaluar el rendimiento del modelo en datos no vistos.

La división se realiza de forma aleatoria, con una proporción típica del 80% para el entrenamiento y el 20% para la prueba.

In [ ]:
from sklearn.model_selection import train_test_split

# División de los datos en conjuntos de entrenamiento y prueba
X = df.drop('variable_objetivo', axis=1)  # Variables predictoras
y = df['variable_objetivo']  # Variable objetivo

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


El parámetro `random_state` garantiza que la división sea reproducible. La variable `test_size=0.2` define que el 20% de los datos se destinen al conjunto de prueba.

---


# Ejemplo Completo de Preprocesamiento


A continuación, se presenta un ejemplo completo que incluye todos los pasos de preprocesamiento.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:

# Cargar datos de ejemplo
df = pd.DataFrame({
    'columna_numerica1': [10, 20, 15, 30],
    'columna_numerica2': [1.5, 3.2, 2.1, 4.0],
    'columna_categorica': ['A', 'B', 'A', 'C'],
    'variable_objetivo': [1, 0, 1, 0]
})

In [ ]:

# Normalización
scaler = MinMaxScaler()
df[['columna_numerica1', 'columna_numerica2']] = scaler.fit_transform(df[['columna_numerica1', 'columna_numerica2']])

In [ ]:

# Codificación de variable categórica
encoder = LabelEncoder()
df['columna_categorica'] = encoder.fit_transform(df['columna_categorica'])

In [ ]:

# División en entrenamiento y prueba
X = df.drop('variable_objetivo', axis=1)
y = df['variable_objetivo']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:

print("Conjunto de Entrenamiento:")
print(X_train)
print("Conjunto de Prueba:")
print(X_test)


Este ejemplo proporciona una visión general de cómo normalizar y codificar datos, así como dividirlos en conjuntos de entrenamiento y prueba.

---

Este contenido asegura una comprensión integral de los pasos básicos de preprocesamiento en `DataFrame` para preparar los datos de manera efectiva para modelos de Machine Learning.

[Video de apoyo hasta aquí]()


### 4. Actividades de Aprendizaje


1. **Exploración de DataFrames**: Cargar un archivo CSV con datos de ejemplo (por ejemplo, el conjunto de datos de Titanic) y explorar sus características principales usando `head()`, `info()`, y `describe()`.


2. **Manipulación Básica**: Seleccionar y modificar columnas, crear nuevas columnas a partir de otras, y filtrar datos basándose en condiciones.

3. **Limpieza de Datos**: Usar métodos para manejar valores nulos y eliminar registros duplicados. Transformar tipos de datos de columnas según se necesite.


4. **Transformación y Agrupación**: Aplicar `groupby()` para obtener estadísticas agregadas y usar `apply()` para crear nuevas características a partir de columnas existentes.

5. **Preparación de Datos para Machine Learning**: Estandarizar las columnas numéricas y codificar las variables categóricas. Dividir el conjunto de datos en entrenamiento y prueba.

# Anexo 1 a la Clase sobre DataFrame

## El atributo `.str` en un dataframe.

El atributo `str` en un DataFrame de pandas es una propiedad que proporciona acceso a una serie de métodos vectorizados para operar sobre datos de tipo string (cadena de texto) en una columna del DataFrame. Esto es útil para realizar operaciones comunes de manipulación y transformación de texto.


### Uso del atributo `str`

El atributo `str` se utiliza en combinación con una columna del DataFrame que contiene datos de tipo string. Aquí hay algunos ejemplos de las operaciones que puedes realizar utilizando `str`:

1. **Convertir a minúsculas o mayúsculas:**

In [54]:
df['columna'].str.lower()  # Convierte todos los caracteres a minúsculas
df['columna'].str.upper()  # Convierte todos los caracteres a mayúsculas

KeyError: 'columna'


2. **Reemplazar partes de una cadena:**

    ```python
    df['columna'].str.replace('antiguo', 'nuevo')  # Reemplaza 'antiguo' por 'nuevo' en cada cadena
    ```


3. **Eliminar espacios en blanco:**

In [49]:
df['columna'].str.strip()  # Elimina espacios en blanco al inicio y al final de cada cadena
df['columna'].str.lstrip()  # Elimina espacios en blanco al inicio de cada cadena
df['columna'].str.rstrip()  # Elimina espacios en blanco al final de cada cadena

KeyError: 'columna'


4. **Dividir cadenas:**

In [ ]:
df['columna'].str.split('separador')  # Divide cada cadena usando el separador especificado y devuelve una lista


5. **Extracción de subcadenas:**

    ```python
    df['columna'].str.slice(start, stop)  # Extrae una subcadena desde la posición 'start' hasta 'stop'
    ```

6. **Comprobar la presencia de un patrón:**

    ```python
    df['columna'].str.contains('patrón')  # Devuelve un booleano indicando si el patrón está presente en cada cadena
    ```


### Ejemplo práctico:

Aquí tienes un ejemplo práctico de cómo usar el atributo `str` para manipular datos de texto en un DataFrame:

```python
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'nombres': [' Alice ', 'Bob', ' Charlie', 'david ', 'Eve']
}
df = pd.DataFrame(data)

# Eliminar espacios en blanco al inicio y al final de cada cadena
df['nombres'] = df['nombres'].str.strip()

# Convertir todos los nombres a mayúsculas
df['nombres'] = df['nombres'].str.upper()

# Reemplazar 'BOB' por 'ROBERT'
df['nombres'] = df['nombres'].str.replace('BOB', 'ROBERT')

print(df)
```

### Salida:
```plaintext
    nombres
0     ALICE
1    ROBERT
2   CHARLIE
3     DAVID
4       EVE
```

### Explicación:
1. **Eliminar espacios en blanco**: `df['nombres'].str.strip()` elimina los espacios en blanco al inicio y al final de cada cadena en la columna `nombres`.
2. **Convertir a mayúsculas**: `df['nombres'].str.upper()` convierte todos los caracteres a mayúsculas.
3. **Reemplazar texto**: `df['nombres'].str.replace('BOB', 'ROBERT')` reemplaza todas las apariciones de 'BOB' con 'ROBERT'.

El atributo `str` es una herramienta poderosa y versátil cuando se trabaja con datos de texto en pandas, permitiendo realizar una amplia gama de operaciones de manera eficiente y vectorizada.

In [44]:
datos = [[' Marco ', 49], [' Joseph ', 16]]
index = ['Padre', 'Hijo']
columnas = ['Nombre', 'Edad'] 

df = pd.DataFrame(datos, index=index, columns=columnas)
df

         Nombre  Edad
Padre    Marco     49
Hijo    Joseph     16

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Padre to Hijo
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  2 non-null      object
 1   Edad    2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 48.0+ bytes

In [38]:
df['Nombre'] = df['Nombre'].str.lower()

In [39]:
df

       Nombre  Edad
Padre   marco    49
Hijo   joseph    16

In [40]:
df['Nombre'] = df['Nombre'].str.upper() # Convertir a mayusculas

In [43]:
df['Nombre'].str.replace('O', 'A')

Padre     MARCA
Hijo     JASEPH
Name: Nombre, dtype: object

In [47]:
df['Nombre'].iloc[0]

' Marco '

In [49]:
df['Nombre'] = df['Nombre'].str.strip()

In [51]:
df['Nombre'].iloc[0]

'Marco'

In [52]:
df

       Nombre  Edad
Padre   Marco    49
Hijo   Joseph    16

In [53]:
df['Nombre'].str.split('a')

Padre    [M, rco]
Hijo     [Joseph]
Name: Nombre, dtype: object

In [2]:
import wrf

ModuleNotFoundError: No module named 'wrf'