In [1]:
import pandas as pd

In [2]:
df_a = pd.DataFrame({'Producto':['A', 'B', 'C'], 'Ventas':[10, 20, 30]})
df_a

  Producto  Ventas
0        A      10
1        B      20
2        C      30

In [3]:
df_b = pd.DataFrame({'Producto':['D', 'E', 'F'], 'Ventas': [40, 50, 60]})
df_b

  Producto  Ventas
0        D      40
1        E      50
2        F      60

In [9]:
df_concat = pd.concat([df_a, df_b], axis = 0, join = 'outer', ignore_index = True) 
df_concat

  Producto  Ventas
0        A      10
1        B      20
2        C      30
3        D      40
4        E      50
5        F      60