In [27]:
import pandas as pd

In [28]:
df_a = pd.DataFrame({'Producto':['A', 'B', 'C'], 'Ventas':[10, 20, 30]}, index = range(1,4))
df_a

  Producto  Ventas
1        A      10
2        B      20
3        C      30

In [29]:
df_b = pd.DataFrame({'Producto':['D', 'E', 'F'], 'Ventas':[40, 50, 60]}, index = range(3))
df_b

  Producto  Ventas
0        D      40
1        E      50
2        F      60

In [31]:
pd.concat([df_a, df_b], axis = 0, join = 'inner', ignore_index = False, keys = ['data1', 'data2'])

        Producto  Ventas
data1 1        A      10
      2        B      20
      3        C      30
data2 0        D      40
      1        E      50
      2        F      60