<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/2_regresion/4_evaluation/4_evaluation_quiz_parcial_regresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### [Video de apoyo a la lectura interactiva y experimental de este cuaderno]()

## [Vínculo al programa del curso:  ]()

# Modelo general de clase: [aula invertida](https://www3.gobiernodecanarias.org/medusa/ecoescuela/pedagotic/aprendizaje-invertido-flipped-classroom/)

## Definición y características de este modelo

## ¿Qué es?  

Flipped Learning o aprendizaje invertido es un enfoque pedagógico en el que:  

* la instrucción directa se realiza fuera del aula y 
* se utiliza el tiempo de clase para llevar a cabo actividades que impliquen el desarrollo de procesos cognitivos de mayor complejidad, en las que son necesarias la ayuda y la experiencia del docente.

## ¿Para qué sirve?  

Mejora el proceso de enseñanza-aprendizaje realizando,   

* fuera del aula, actividades de aprendizaje sencillas (observar, memorizar, resumir, etc.) y, 
* en el aula, actividades más complejas (razonar, examinar, priorizar, argumentar, proponer, etc.) que requieren la interacción entre iguales y la ayuda del docente como facilitador.

<img src = 'https://github.com/marco-canas/7_didactica_ciencia_datos/blob/main/propuesta/unidad_didac/atributos_aprendizaje_invertido.png?raw=true'>

# Proceso Flipped Learning

## Fuera del Aula

### Docente:

* Diseña y planea el proceso de enseñanza-aprendizaje del aula, integrando estrategias, modelos de enseñanza y metodologías (aprendizaje basado en proyectos, aprendizaje cooperativo y colaborativo,…).  

* Diseña y planea actividades que se realizarán fuera del aula (ver vídeos, cumplimentar cuestionarios,…).  

* Selecciona e integra la tecnología en actividades de aprendizaje activo.  

* Diseña actividades de evaluación que promuevan el aprendizaje del alumnado.

### Alumnado:

* Accede, cuantas veces necesite, a las actividades facilitadas por el profesorado.
* Realiza las actividades propuestas.

## En el Aula

### Docente:

* Guía y facilita los procesos de aprendizaje, atendiendo a la diversidad.
* Retroalimenta el desempeño de los equipos/grupos y del alumnado individualmente.
* Genera espacios para la coevaluación y autoevaluación.

### Alumnado:

* Realiza las actividades (debates, exposiciones orales, informes, diario de aprendizaje, cuaderno de trabajo cooperativo,…).
* Recibe retroalimentación inmediata del profesorado y de sus compañeros y compañeras.
* Accede, si fuera necesario, a las actividades previas facilitadas por el profesorado.

## Fomento de la lectura literaria asociada a Ingeniería agropecuaria y licenciatura en Matemáticas

John Allen Paulos. El hombre anumérico. El analfabetismo matemático y sus consecuencias. 

"Las mates siempre fueron mi asignatura más floja." 

<<Un millón de dólares, mil millones o un billón. No importa cuánto siempre y cuando hagamos algo por resolver el problema.>>

<< Jerry y yo no iremos a Europa, con tantos terroristas...>>  

El anumerismo, o incapacidad de menejar cómodamente los conceptos fundamentales de número y azar, atormenta a demasiados ciudadanos que, por lo demás, pueden ser perfectamente instruidos.

# Evaluación de habilidades asociadas a la construcción de modelos de regresión

## Objetivo de aprendizaje (Enunciar, de manera corta sencilla y clara para todos los asistentes)

* Evaluar, coevaluar y autoevaluarse en cuanto a la adquisición de habilidades para construir modelos de regresión

## Establecimiento de prerrequisitos conceptuales para alcanzar el objetivo de aprendizaje trazado.   

(Elabore una lista de preguntas al rededor de los conceptos que consideres necesarios para empezar la clase).  

1. 
2. 
3.

# Para el diseño de la clase tenga en cuenta algunos problemas de aprendizaje

## Secuencia conceptual de actividades evaluativas

## Punto 1

De los siguientes dataset listados con su url de github: 
* seleccione al menos una variable objetivo adecuada para modelo de regresión. 
* Construir el DataFrame asociados a este dataset
* Utilizar los métodos `head()`, `tail()`, `info()`, `value_counts()`, `.describe()`; para hacer las interpretaciones que lleven a un primer acercamiento al conocimiento de los datos para los que esté construyendo su modelo de regresión. 
* Selecciones las variables categóricas del datasets(Utilice para ello el método info()). 
* De cada variable categórica diga cual es la categoría más frecuente. (Para ello utilice el método `.value_couts(ascending = False)` para que ordente las subcategorias en orden descendente con respecto a la frecuencia.)

Recuerde para ello la definición de regresión que hemos dado en este curso. 

1.  [Precio de carros](https://raw.githubusercontent.com/marco-canas/7_didactica_ciencia_datos/main/datasets/germany_cars/germany_cars.csv)
2.  
3.  


Una variable adecuacuada para regresión es la temperatura puede ser tratada como una variable aleatoria continua, ya que puede tomar cualquier valor dentro de un rango de temperaturas posibles y no solo valores discretos. Además, la temperatura también puede ser modelada como una variable aleatoria normal, ya que en muchos casos sigue una distribución normal o gaussiana.

Y recuerde que variables categóricas son las apropiadas para tareas de clasificación no de regresión: En estadística, una variable categórica es una variable que toma valores de un conjunto limitado y predefinido de categorías o grupos. Estas categorías pueden ser cualitativas o cuantitativas, pero no tienen un orden inherente entre ellas.

Por ejemplo, una variable categórica podría ser el género de una persona, con dos posibles categorías: masculino o femenino. Otra variable categórica podría ser el tipo de vehículo, con varias categorías como automóvil, camión, motocicleta, etc.

Las variables categóricas son distintas de las variables numéricas, que tienen un valor numérico continuo o discreto. En el análisis estadístico, las variables categóricas se pueden analizar utilizando técnicas como tablas de contingencia, pruebas de chi-cuadrado y análisis de varianza (ANOVA).

El precio de los carros se puede tratar como una variable aleatoria continua, ya que puede tomar cualquier valor dentro de un rango de precios posibles y no solo valores discretos.

Además, el precio de los carros puede ser modelado como una variable aleatoria no negativa, ya que los precios no pueden ser negativos. Dependiendo de la distribución de precios en una población de carros, es posible que el precio pueda ser modelado utilizando una distribución normal, lognormal u otra distribución continua. En el análisis estadístico, se pueden utilizar diversas técnicas para analizar y comparar los precios de los carros, como pruebas t, ANOVA, regresión lineal, etc.

# Solución de la evaluación

1. Importa pandas
2. crea la variable url con la dirección en GitHub de los datos
3. crea una variable carros que guardará el dataframe creado por la función .read_csv()
4. Imprime el DataFrame

In [1]:
import pandas as pd 

url = "https://raw.githubusercontent.com/marco-canas/7_didactica_ciencia_datos/main/datasets/germany_cars/germany_cars.csv"
carros = pd.read_csv(url) 
carros

,mileage,make,model,fuel,gear,offerType,price,hp,year
0,235000,BMW,316,Diesel,Manual,Used,6800,116.0,2011
1,92800,Volkswagen,Golf,Gasoline,Manual,Used,6877,122.0,2011
2,149300,SEAT,Exeo,Gasoline,Manual,Used,6900,160.0,2011
3,96200,Renault,Megane,Gasoline,Manual,Used,6950,110.0,2011
4,156000,Peugeot,308,Gasoline,Manual,Used,6950,156.0,2011
...,...,...,...,...,...,...,...,...,...
46400,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021
46401,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021
46402,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021
46403,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021
46404,99,Fiat,500,Electric/Gasoline,Manual,Pre-registered,12990,71.0,2021

# Inferencias de la exploración de los datos

In [7]:
carros.make.value_counts(ascending=False).count()

77

In [8]:
carros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46405 entries, 0 to 46404
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   mileage    46405 non-null  int64
 1   make       46405 non-null  object
 2   model      46262 non-null  object
 3   fuel       46405 non-null  object
 4   gear       46223 non-null  object
 5   offerType  46405 non-null  object
 6   price      46405 non-null  int64
 7   hp         46376 non-null  float64
 8   year       46405 non-null  int64
dtypes: float64(1), int64(3), object(5)
memory usage: 3.2+ MB

# Evaluación 2 Constituir un modelo de regresión con datos meteorológicos de Antioquia mira su cielo.

1. Obtenga los datos de [Antioquia mira su cielo](https://github.com/marco-canas/7_didactica_ciencia_datos/tree/main/datasets/antioquia_mira_su_cielo)

In [1]:
import pandas as pd # obtener los datos en forma de dataframe
direccion  = "https://raw.githubusercontent.com/marco-canas/7_didactica_ciencia_datos/main/datasets/antioquia_mira_su_cielo/A2022M12/DatosEstacion2022-12-14.csv"# cree una variable con la ubicación de los datos

In [2]:
df = pd.read_csv(direccion)  # leer y crea un dataframe de nombre df

In [3]:
df

,Tiempo Sistema,Bar Trend,Next Record,Barometer,Inside Temperature,Inside Humidity,Outside Temperature,Wind Speed,10 Min Avg Wind Speed,Wind Direction,...,Soil & Leaf Alarms,Transmitter Battery Status,Console Battery Voltage,Forecast Icons,Forecast Rule number,Time of Sunrise,Time of Sunset,<LF> = 0x0A,<CR> = 0x0D,CRC
0,2022-12-14 00:00:00,O,1956,29823,868,72,782,1,0,312,...,0,0,778,6,45,606,1746,10,13,58065
1,2022-12-14 00:01:00,O,1956,29822,867,72,782,1,0,309,...,0,0,778,6,45,606,1746,10,13,16103
2,2022-12-14 00:02:00,O,1956,29822,867,73,782,0,0,309,...,0,0,778,6,45,606,1746,10,13,28375
3,2022-12-14 00:03:06,O,1956,29824,867,73,782,0,0,309,...,0,0,778,6,45,606,1746,10,13,57448
4,2022-12-14 00:04:00,O,1956,29823,867,73,781,0,0,309,...,0,0,778,6,45,606,1746,10,13,60213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,2022-12-14 23:55:00,O,2003,29804,869,72,789,1,0,15,...,0,0,778,6,75,606,1746,10,13,37185
1436,2022-12-14 23:56:00,O,2003,29802,869,72,789,0,0,15,...,0,0,778,6,75,606,1746,10,13,22194
1437,2022-12-14 23:57:01,O,2003,29803,869,72,789,0,0,15,...,0,0,778,6,75,606,1746,10,13,49735
1438,2022-12-14 23:58:00,O,2003,29803,869,72,789,2,0,46,...,0,0,779,6,75,606,1746,10,13,21720
1439,2022-12-14 23:59:00,O,2003,29803,869,72,789,0,0,45,...,0,0,778,6,75,606,1746,10,13,50638

* Visualización tabular

Naturaleza de las variables

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tiempo Sistema               1440 non-null   object
 1   Bar Trend                    1440 non-null   object
 2   Next Record                  1440 non-null   int64
 3   Barometer                    1440 non-null   int64
 4   Inside Temperature           1440 non-null   int64
 5   Inside Humidity              1440 non-null   int64
 6   Outside Temperature          1440 non-null   int64
 7   Wind Speed                   1440 non-null   int64
 8   10 Min Avg Wind Speed        1440 non-null   int64
 9   Wind Direction               1440 non-null   int64
 10  Extra Temperatures           1440 non-null   int64
 11  Soil Temperatures            1440 non-null   int64
 12  Leaf Temperatures            1440 non-null   int64
 13  Outside Humidity             1440 non-null   int64
 14  Extra Humidties              1440 non-null   int64
 15  Rain Rate                    1440 non-null   int64
 16  UV                           1440 non-null   int64
 17  Solar Radiation              1440 non-null   int64
 18  Storm Rain                   1440 non-null   int64
 19  Start Date of current Storm  1440 non-null   int64
 20  Day Rain                     1440 non-null   int64
 21  Month Rain                   1440 non-null   int64
 22  Year Rain                    1440 non-null   int64
 23  Day ET                       1440 non-null   int64
 24  Month ET                     1440 non-null   int64
 25  Year ET                      1440 non-null   int64
 26  Soil Moistures               1440 non-null   int64
 27  Leaf Wetnesses               1440 non-null   int64
 28  Inside Alarms                1440 non-null   int64
 29  Rain Alarms                  1440 non-null   int64
 30  Outside Alarms               1440 non-null   int64
 31  Extra Temp/Hum Alarms        1440 non-null   int64
 32  Soil & Leaf Alarms           1440 non-null   int64
 33  Transmitter Battery Status   1440 non-null   int64
 34  Console Battery Voltage      1440 non-null   int64
 35  Forecast Icons               1440 non-null   int64
 36  Forecast Rule number         1440 non-null   int64
 37  Time of Sunrise              1440 non-null   int64
 38  Time of Sunset               1440 non-null   int64
 39  <LF> = 0x0A                  1440 non-null   int64
 40  <CR> = 0x0D                  1440 non-null   int64
 41  CRC                          1440 non-null   int64
dtypes: int64(40), object(2)
memory usage: 472.6+ KB

In [8]:
df

,Tiempo Sistema,Bar Trend,Next Record,Barometer,Inside Temperature,Inside Humidity,Outside Temperature,Wind Speed,10 Min Avg Wind Speed,Wind Direction,...,Soil & Leaf Alarms,Transmitter Battery Status,Console Battery Voltage,Forecast Icons,Forecast Rule number,Time of Sunrise,Time of Sunset,<LF> = 0x0A,<CR> = 0x0D,CRC
0,2022-12-14 00:00:00,O,1956,29823,868,72,782,1,0,312,...,0,0,778,6,45,606,1746,10,13,58065
1,2022-12-14 00:01:00,O,1956,29822,867,72,782,1,0,309,...,0,0,778,6,45,606,1746,10,13,16103
2,2022-12-14 00:02:00,O,1956,29822,867,73,782,0,0,309,...,0,0,778,6,45,606,1746,10,13,28375
3,2022-12-14 00:03:06,O,1956,29824,867,73,782,0,0,309,...,0,0,778,6,45,606,1746,10,13,57448
4,2022-12-14 00:04:00,O,1956,29823,867,73,781,0,0,309,...,0,0,778,6,45,606,1746,10,13,60213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,2022-12-14 23:55:00,O,2003,29804,869,72,789,1,0,15,...,0,0,778,6,75,606,1746,10,13,37185
1436,2022-12-14 23:56:00,O,2003,29802,869,72,789,0,0,15,...,0,0,778,6,75,606,1746,10,13,22194
1437,2022-12-14 23:57:01,O,2003,29803,869,72,789,0,0,15,...,0,0,778,6,75,606,1746,10,13,49735
1438,2022-12-14 23:58:00,O,2003,29803,869,72,789,2,0,46,...,0,0,779,6,75,606,1746,10,13,21720
1439,2022-12-14 23:59:00,O,2003,29803,869,72,789,0,0,45,...,0,0,778,6,75,606,1746,10,13,50638

In [10]:
df["Tiempo Sistema"]

0       2022-12-14 00:00:00
1       2022-12-14 00:01:00
2       2022-12-14 00:02:00
3       2022-12-14 00:03:06
4       2022-12-14 00:04:00
               ...
1435    2022-12-14 23:55:00
1436    2022-12-14 23:56:00
1437    2022-12-14 23:57:01
1438    2022-12-14 23:58:00
1439    2022-12-14 23:59:00
Name: Tiempo Sistema, Length: 1440, dtype: object

In [9]:
df.Tiempo Sistema

SyntaxError: invalid syntax (3524759633.py, line 1)

In [15]:
type(df["Tiempo Sistema"][2])

str

* Visualización gráfica

#

## Mapa conceptual de la clase elaborado en CMapTools

<img src = ''>

## Tareas para realizar antes de la clase

1. Ver los videos respectivos []()
2. Memorizar las definiciones []()
3. Sintetizar o resumir la información en mapas conceptuales. []()

# Tareas para realizar en clase

* Modelación matemática 
* Trabajo en equipos

# Tareas para realizar después de la realización de la clase

* Actividades de memorización: 
  - escucha reiterada de grabaciones de formulas y resultados científicos. 
  - relectura de notas. 
  - ejercicios de mayor complejidad.

## Dificultades de aprendizaje detectados durante la clase

## Estrategias propuestas para la solución de las dificultades de aprendizaje detectadas

## Cuestionario para realizar labores de memorización y observación,  a la síntesis de la información

1. Cuales son los tipos de datos
2. cuáles son las estructuras de datos
3. Cómo se determinan la naturaleza de las variables aleatorias en el dataset. 
4. Cómo se accede a la información o a los datos en un dataframe

## Grabaciones en audio para fomentar la capacidad de memorizar enunciados de teoremas y resultados científicos y la capacidad de parafrasear estos resultados.

Se dispondrá de un lugar en el drive asociuado al correo institucional de la Universidad Nacional del Profesor Marso para albergar los archivosd de audio de fomento a la memoirización, enunciación y parafraseo de los resultados científicos, prtopiedades, reglas, etc. 

* [Vocaroo]()
* [acceso a infomación en una dafaframe](https://voca.ro/1iJL0EnWxBC0)

### Comparta sus cuadernos y videos, evidencias de su aprendizaje [aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUMEMwTEZVMzEwVVBPTElWNVg5OVEyWUhMUy4u)

In [16]:
df["Tiempo Sistema"]

0       2022-12-14 00:00:00
1       2022-12-14 00:01:00
2       2022-12-14 00:02:00
3       2022-12-14 00:03:06
4       2022-12-14 00:04:00
               ...
1435    2022-12-14 23:55:00
1436    2022-12-14 23:56:00
1437    2022-12-14 23:57:01
1438    2022-12-14 23:58:00
1439    2022-12-14 23:59:00
Name: Tiempo Sistema, Length: 1440, dtype: object

# Vocabulary

## Mapa conceptual que vincula los conceptos asoaciados al objetivo de aprendizaje

## Quiz de 5 minutos para ejercitación y adquisición de habilidades

## Referentes

* [stewart precálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ERHIq62I6qFNrmxy6LZb8ZMBci7kUsyNME1nIh9yCBMJ_w?e=0zMSla)  

* [stewart cálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/EZgXZjAp8QxPqOAim2hs6LcBNPLGjSHf-xwYnUVYkwa04w?e=RZdTCy)  

* [larson](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ES71ChFeO9ZDhW3TwC5Ijk8BjxUK3Pdqz_fjHxTTFAfIAg?e=VDEjfu)

* [uzcategui](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ETDikm-lVl1Or8XoEo9oyh0BEti9Zs8le-f0D-dBdtZmbA?e=bBsoyQ)

* [Recomendación de la UNESCO sobre ciencia abierta](https://unesdoc.unesco.org/ark:/48223/pf0000379949_spa)

### [Evaluamos al profesor Marco Cañas Aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUREJPV1kxUk1JV1ozTFJIQVNIQjY5WEY3US4u)

## [Evaluación luego de alcanzar estos objetivos de aprendizaje]()

### Continue su aprendizaje en la siguiente clase a través del siguiente [vínculo]()

# Conjeturas pedagógicas fruto de la aplicación del modelo de aprendizaje invertido y del enfoque hacia la ciencia de datos con python

1. Todo cálculo o resultado debe ser interpretado en una línea markdown del cuaderno Jupyter, inmediatamente después de la enunciación del resultado y después de la presentación de una tabla o gráfico bidimensional, de tal menera que el estudiante explicite la comprensión verbal del resultado y las inferencias o estrategias que este resultado le sugieren.

## Agradecimientos  

Doy gracias a Dios por la vida de mi Hijo Joseph Cañas Osorio y la madurez que ha alcanzado.

Y a mi esposa Yasmira por su apoyo, orientación y acompañamiento.